### PR TITLE
add summarize config

### PR DESCRIPTION
**Pull request by chottuthejimmy**
This much should be fine for me, there are still some spots where its being called irrespective of the config like [here](https://github.com/testdriverai/testdriverai/blob/4cf4af2849338555f22549544ddfed37eacaa5b0/index.js#L834C2-L834C39) and [here](https://github.com/testdriverai/testdriverai/blob/4cf4af2849338555f22549544ddfed37eacaa5b0/index.js#L846) but they are actually helpful and would need it all the time. 

lmk.

### CODE REVIEW

**Review by ianjennings — CHANGES_REQUESTED** [review]
Rather than repeating the logic, it makes more sense to put the `config` check within the `summarize` function.

**Comment by chottuthejimmy** [comment]
> Rather than repeating the logic, it makes more sense to put the `config` check within the `summarize` function.

But then as I said, I would still it at some places like [here](https://github.com/testdriverai/testdriverai/blob/4cf4af2849338555f22549544ddfed37eacaa5b0/index.js#L834C2-L834C39) and [here](https://github.com/testdriverai/testdriverai/blob/4cf4af2849338555f22549544ddfed37eacaa5b0/index.js#L846) even when its false.

**Comment by chottuthejimmy** [comment]
@ianjennings let me know what to do.

**Comment by ianjennings** [comment]
- this is going to break prod when it deploys unless we update `testdriver-proxy` because it will disable summaries
- I feel like the variable name is not great because it doesn't disable them globally. it should disable them globally or name it something else

**Comment by chottuthejimmy** [comment]
I think let's just hold this thing here. 
`4.1` is a bit different and I haven't had enough hands on to decide what to / whether to do something about this.

**Pull request closed without merging**
